#!/bin/bash
#
# Copyright 2019 Red Hat, Inc.
#
# NAME
#     lab-console-write - Grading script for RH134
#                         Console Write Guided Exercise.
#
# SYNOPSIS
#     lab-console-write {start|finish}
#
#        start   - prepare the system for starting the lab
#        finish  - perform post-lab cleanup
#
# DESCRIPTION
#     This script, based on singular argument, either does start or finish for
#     the RH134 Console Write Guided Exercise.
#
# CHANGELOG
#   * Wed Mar 14 2019 Adrian Andrade <aandrade@redhat.com>
#   - original code

PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Initialize and set some variables
run_as_root='true'
target='servera'
reqd_package='vim-enhanced'

# This defines which subcommands are supported (start, grade, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(start finish)


function lab_start {

  print_header 'Starting lab.'

  print_line "Preparing ${target} for lab exercise work:"
  print_line

  pad " · Verifying that ${target} is running: "
  if host_reachable ${target}
  then
    print_SUCCESS
  else
    print_FAIL
  fi
  
  pad " · Verifying that ${target} has required packages: "
  ${ssh} ${target} "yum install -y  ${reqd_package}"
  print_SUCCESS
}

function lab_finish {

  print_header "Completing the lab on ${target}:"
  print_line
  print_line 'Lab finished.'
  print_line

}

############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
