#!/bin/bash
#
# Copyright 2019 Red Hat, Inc.
#
# NAME
#     lab-users-manage - grading script for RH124 Managing Local User Accounts
#
# SYNOPSIS
#     lab-users-manage {start|finish}
#
#        start   - prepare the system for starting the lab
#        finish  - perform post-lab cleanup
#
# DESCRIPTION
#     This script, based on singular argument, either does start
#     or finish for the Managing Local User Accounts Guided Exercise. 
#
# CHANGELOG
#   * Tue Jan 23 2019 Saumik Paul <saumik@redhat.com>
#   - original code

PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Initialize and set some variables
run_as_root='true'
target='servera'
ge_user1='operator1'
ge_user2='operator2'
ge_user3='operator3'
ge_user_pw='redhat'
passwd='/etc/passwd'
shadow='/etc/shadow'

# This defines which subcommands are supported (start, grade, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(start finish)


function lab_start {

  reqd_package='shadow-utils'        # Just an example

  print_header 'Starting lab.'

  print_line "Preparing ${target} for lab exercise work:"
  print_line
  host_reachable ${target}


  # Check for lab prerequisites (perhaps a required package?).
  if ! ${ssh} ${target} "rpm -q --quiet ${reqd_package}"
  then
    pad " · Error - ${reqd_package} is not installed on ${target}"
    print_FAIL
  else
    pad " · Ensuring no operator exists on ${target}"
    if ! ${ssh} ${target} "grep ${ge_user1} ${passwd} ${shadow}" &&
       ! ${ssh} ${target} "grep ${ge_user2} ${passwd} ${shadow}" &&
       ! ${ssh} ${target} "grep ${ge_user3} ${passwd} ${shadow}"
    then
      print_SUCCESS
    else
      ${ssh} ${target} userdel -r ${ge_user1}
      ${ssh} ${target} userdel -r ${ge_user2}
      ${ssh} ${target} userdel -r ${ge_user3}
      if ! ${ssh} ${target} "grep ${ge_user1} ${passwd} ${shadow}" &&
	 ! ${ssh} ${target} "grep ${ge_user2} ${passwd} ${shadow}" &&
	 ! ${ssh} ${target} "grep ${ge_user3} ${passwd} ${shadow}"
      then
	print_SUCCESS
      else
	print_FAIL
      fi
    fi

    print_line
  fi
}

function lab_finish {

  print_header "Completing the lab on ${target}:"
  host_reachable ${target}

  pad " · Deleting ${ge_user1}, ${ge_user2} and ${ge_user3} from ${target}"
  ${ssh} ${target} "userdel -r ${ge_user1}; userdel -r ${ge_user2}; userdel -r ${ge_user3}"
  if ! ${ssh} ${target} "grep ${ge_user1} ${passwd} ${shadow}" &&
     ! ${ssh} ${target} "grep ${ge_user2} ${passwd} ${shadow}" &&
     ! ${ssh} ${target} "grep ${ge_user3} ${passwd} ${shadow}"
  then
    print_SUCCESS
  else
    print_FAIL
  fi    

  print_line
  print_line 'Lab finished.'
  print_line
}

############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
