#!/bin/bash
#
# Copyright 2019, 2020 Red Hat, Inc.
#
# NAME
#     lab-boot-resetting - grading script for RH134 Resetting the Root
#                          Password guided exercise
#
# SYNOPSIS
#     lab-boot-resetting {start|finish}
#
#        start   - prepare the system for starting the lab
#        finish  - perform post-lab cleanup
#
# DESCRIPTION
#     This script, based on singular argument, either does start or finish for
#     the Resetting the Root Password guided exercise.
#
# CHANGELOG
#   * Tue Aug 25 2020 Herve Quatremain <hquatrem@redhat.com>
#   - fixing UEFI boot issues
#   * Tue Mar 26 2019 Herve Quatremain <hquatrem@redhat.com>
#   - original code


PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Initialize and set some variables
run_as_root='true'
target='servera'

# This defines which subcommands are supported (start, grade, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(start finish)


function lab_start {

  print_header 'Starting lab.'

  print_line "Preparing ${target} for lab exercise work:"
  print_line
  host_reachable ${target}

  rhel_backup ${target} /boot/efi/EFI/redhat/grub.cfg /boot/efi/EFI/redhat/grubenv /etc/default/grub /boot/grub2/grub.cfg /boot/grub2/grubenv /boot/loader

  pad " · Updating GRUB2 countdown on ${target}"
  ${ssh} ${target} "sed -i -e 's/GRUB_TIMEOUT=.*/GRUB_TIMEOUT=15/' -e '/GRUB_CMDLINE_LINUX=/s/console=[^ ]*//g' /etc/default/grub"
  print_SUCCESS

  rhel_grub2_mkconfig ${target}

  pad " · Updating root password on ${target}"
  if ${ssh} ${target} "echo 424242424242 | passwd --stdin root"
  then
    print_SUCCESS
  else
    print_FAIL
  fi

  print_line
}


function lab_finish {

  print_header "Cleaning up the lab on ${target}:"
  host_reachable ${target}

  pad " · Reseting root password on ${target}"
  if ${ssh} ${target} "echo redhat | passwd --stdin root"
  then
    print_SUCCESS
  else
    print_FAIL
  fi

  rhel_restore ${target}

  print_line
  print_line 'Lab finished.'
  print_line
}

############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
