#!/bin/bash
#
# Copyright 2020 Red Hat, Inc.
#
# NAME
#     lab-containers-advanced - lab script for RH134 Performing Advanced
#             Container Management guided exercise.
#
# SYNOPSIS
#     lab-containers-advanced {start | finish}
#
#        start   - prepare the system for starting the lab
#        finish  - perform post-lab cleanup
#
# DESCRIPTION
#     This script, based on singular argument, either does start
#     or finish for the guided exercise.
#
# CHANGELOG
#   * Mon Aug 31 2020 Victor Costea <vcostea@redhat.com>
#   - Peer review fixes
#   * Wed Aug 26 2020 Victor Costea <vcostea@redhat.com>
#   - Based on Herve and Ed's original code
#   - Added install and remove of mariadb client to servera
#   * Thu Aug 20 2020 Herve Quatremain <hquatrem@redhat.com>
#   - original code
#   * Thu Aug 20 2020 Ed Parenti <eparenti@redhat.com>
#   - revised per testing and added a check for images in the registry

PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Initialize and set some variables
run_as_root='true'
target='servera'

reqd_package='mariadb'

# This defines which subcommands are supported (start, grade, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(start finish)

function lab_start {

  print_header 'Starting guided exercise.'

  print_line "Preparing ${target} for guided exercise work:"
  print_line
  host_reachable ${target}

  rhel_containers_check_quay

  rhel_containers_deploy_client ${target}

  rhel_containers_inspect_image admin redhat321 registry.lab.example.com/rhel8/mariadb-103:1-102 Digest
  rhel_containers_inspect_image admin redhat321 registry.lab.example.com/rhel8/httpd-24:1-105 Digest

  # Install MariaDB client on servera
  pad " · Checking that ${reqd_package} client is installed on ${target}"
  cmd1="yum -y install ${reqd_package}"
  if  ${ssh} ${target} "rpm -q --quiet ${reqd_package}"; then
    print_SUCCESS
  elif  ${ssh} ${target} "${cmd1}"; then
    print_SUCCESS
  else
    print_FAIL
  fi

  pad " · Deploying the help files on ${target}"
  ${ssh} ${target} "mkdir -p /tmp/${problem_name}"
  cat <<EOF | ${ssh} ${target} "cat > /tmp/${problem_name}/create-mydb.txt"
podman run -d --name mydb -e MYSQL_USER=user1 -e MYSQL_PASSWORD=redhat -e MYSQL_DATABASE=items -e MYSQL_ROOT_PASSWORD=redhat -p 3306:3306 registry.lab.example.com/rhel8/mariadb-103:1-102
EOF
  print_SUCCESS

  print_line
}

function lab_finish {

  print_header "Cleaning up the guided exercise on ${target}:"
  host_reachable ${target}

  rhel_containers_undeploy_client ${target}

  # Remove mariadb client and student's .mysql_history file from servera
  pad " · Removing ${reqd_package} client from ${target}."
  cmd1="yum remove -y ${reqd_package}"
  cmd2="rm -f /home/student/.mysql_history"
  if ${ssh} ${target} "${cmd1}"; then
    ${ssh} ${target} "${cmd2}"
    print_SUCCESS
  else
    print_FAIL
  fi

  print_line
  print_line 'Guided exercise finished.'
  print_line
}

############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"

