#!/bin/bash
#
# Copyright 2019 Red Hat, Inc.
#
# NAME
#     lab-cli-desktop - grading script for RH124 Accessing the Command Line
#     Using the Desktop exercise
#
# SYNOPSIS
#     lab-template {start|finish}
#
#        start   - prepare the system for starting the lab
#        finish  - perform post-lab cleanup
#
# DESCRIPTION
#     This script, based on singular argument, either does start,
#     or finish for the CH02-Accessing the Command Line Using the Desktop.
#
# CHANGELOG
#   * Mon Dec 21 2019 Snehangshu Karmakar <snehk@redhat.com>
#   - original code

PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Initialize and set some variables
run_as_root='true'
target='workstation'

declare -a valid_commands=(start finish)

function lab_start {

  print_header 'Starting lab.'

  print_line "Preparing ${target} for lab exercise work:"
  print_line
  #host_reachable ${target}
  pad " · Nothing to setup"
  print_SUCCESS

}

function lab_finish {

  print_header "Cleaning up the lab on ${target}:"
  #host_reachable ${target}

  pad ' · Resetting student password'
  if echo "student" | passwd --stdin student; then
    print_SUCCESS
  else
    print_FAIL
  fi  
  print_line
  print_line 'Lab finished.'
  print_line
}

############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
