#!/bin/bash
#
# Copyright 2019 Red Hat, Inc.
#
# NAME
#     lab-help-review - grading script for RH124 Getting Help 
#
# SYNOPSIS
#     lab-edit-review {start|grade|finish}
#
#        start   - prepare the system for starting the lab
#        grade   - perform evaluation steps on the system
#        finish  - perform post-lab cleanup
#
# DESCRIPTION
#     This script, based on singular argument, either does start, grading,
#     or finish for the particular lab of awesomeness.
#
# CHANGELOG
#   * Tue Feb 26 2019 Fiona Allen <fallen@redhat.com>
#   - original code

PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Initialize and set some variables
run_as_root='true'
target='servera'
file='/home/student/passwd.ps'

# This defines which subcommands are supported (start, grade, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(start grade finish)


function lab_start {

  print_header 'Starting lab.'

  print_line "Preparing workstation for lab exercise work:"
  print_line

  pad " · Verifying that ${target} is running: "
  if host_reachable ${target}
  then
    print_SUCCESS
  else
    print_FAIL
  fi

  pad " · Running man update: "
  if sudo mandb -c
  then
    print_SUCCESS
  else
    print_FAIL
  fi

  pad " · Ensuring ${file} does not exist: "
  if [ -f $file ]
  then
    rm ${file} 
    print_SUCCESS
  else
    print_SUCCESS
  fi

  print_line

}

function lab_grade {

  print_line

  pad " · Ensuring ${file} exists: "
  if [ -f $file ]
  then 
    print_PASS
  else
    print_FAIL
  fi

  # Overall grade
  print_line
  pad 'Overall lab grade'
  if [[ ${fail_count} -eq 0 ]]
  then
    print_PASS
  else
    print_FAIL
  fi

}

function lab_finish {

  print_header "Completing the lab on workstation:"
  host_reachable ${target}

  pad " · Remove ${file}: "
  if [ -f $file ]
  then
    rm -f ${file} && print_SUCCESS
    else
    if [ ! -f $file ]
    then
      print_SUCCESS
    else
      print_FAIL
    fi
  fi

  print_line
  print_line 'Lab finished.'
  print_line

}

############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
