#!/bin/bash
#
# Copyright 2019 Red Hat, Inc.
#
# NAME
#     lab-support-cockpit - grading script for RH124 RHEL8
#                           Getting Help from Red Hat Customer Portal
#
# SYNOPSIS
#     lab-support-cockpit {start|finish}
#
#        start   - prepare the system for starting the lab
#        finish  - perform post-lab cleanup
#
# DESCRIPTION
#     This script, based on singular argument, either does start, or finish for
#     the Remote Server Analysis and Management with Cockpit guided exercise.
#
# CHANGELOG
#   * Tue Mar 04 2019 Fiona Allen <fallen@redhat.com>
#   - original code

PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Initialize and set some variables
run_as_root='true'
target='servera'
targetb='serverb'

# This defines which subcommands are supported (start, grade, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(start finish)


function lab_start {

  print_header 'Starting lab.'

  pad " · Verifying that ${target} is running: "
  if host_reachable ${target}
  then
    print_SUCCESS
  else
    print_FAIL
  fi

  pad " · Ensuring Cockpit is enabled and started: "
  if ${ssh} ${target} systemctl enable --now cockpit.socket
  then
    print_SUCCESS
  else
    print_FAIL
  fi

  

  print_line
}

function lab_finish {

  print_header "You have completed attempting the guided exercise."

  pad " · Checking ${target}."
  if host_reachable ${target}
  then
    print_SUCCESS
  else
    print_FAIL
  fi

  print_line
  print_line 'Lab finished.'
  print_line
}

############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
