#!/bin/bash
#
# Copyright 2020 Red Hat, Inc.
#
# NAME
#     lab-containers-storage - grading script for RH134 Attaching Persistent
#                               Storage to a Container guided exercise
#
# SYNOPSIS
#     lab-containers-storage {start|finish}
#
#        start   - prepare the system for starting the lab
#        finish  - perform post-lab cleanup
#
# DESCRIPTION
#     This script, based on singular argument, either does start or
#     finish for the Attaching Persistent Storage to a Container guided
#     exercise
#
# CHANGELOG
#   * Fri Aug 28 2020 Herve Quatremain <hquatrem@redhat.com>
#   - original code

PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Initialize and set some variables
run_as_root='true'
target='servera'
persistent_dir='/home/student/webcontent'

# This defines which subcommands are supported (start, grade, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(start finish)


function lab_start {

  print_header 'Starting lab.'

  print_line "Preparing ${target} for lab exercise work:"
  print_line
  host_reachable ${target}

  rhel_containers_check_quay

  rhel_containers_inspect_image admin redhat321 registry.lab.example.com/rhel8/httpd-24:1-98 Digest
  rhel_containers_inspect_image admin redhat321 registry.lab.example.com/rhel8/httpd-24:1-105 Digest

  rhel_containers_deploy_client ${target}

  print_line
}

function lab_finish {

  print_header "Cleaning up the lab on ${target}:"
  host_reachable ${target}

  rhel_containers_undeploy_client ${target}

  pad " · Removing exercise directories on ${target}"
  ${ssh} ${target} "rm -rf ${persistent_dir}"
  print_SUCCESS

  print_line
  print_line 'Lab finished.'
  print_line
}

############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
