#!/bin/bash
#
# Copyright 2019 Red Hat, Inc.
#
# NAME
#     lab-log-preserve - grading script for RH124 Reviewing System Journal Entries 
#
# SYNOPSIS
#     lab-log-preserve {start|finish}
#
#        start   - prepare the system for starting the lab
#        finish  - perform post-lab cleanup
#
# DESCRIPTION
#     This script, based on singular argument, either does start
#     or finish for the particular lab of awesomeness.
#
# CHANGELOG
#   * Mon Feb 18 2019 Saumik Paul <saumik@redhat.com>
#   - original code

PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Initialize and set some variables
run_as_root='true'
targeta='servera'
#targetb='serverb'
#known_hosts=/home/student/.ssh/known_hosts
#ge_user1='operator1'
#ge_user2='operator2'
#ge_user3='operator3'
#ge_user_pw='redhat'
#passwd='/etc/passwd'
#shadow='/etc/shadow'
log_preserve_conf='/etc/systemd/journald.conf'
#log_debug_file='/var/log/messages-debug'

# This defines which subcommands are supported (start, grade, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(start finish)


function lab_start {

  reqd_package='systemd'        # Just an example

  print_header 'Starting lab.'

  print_line "Preparing ${targeta} for lab exercise work:"
  print_line
  host_reachable ${targeta}


  # Check for lab prerequisites (perhaps a required package?).
  if ! ${ssh} ${targeta} "rpm -q --quiet ${reqd_package}"
  then
    pad " · Error - ${reqd_package} is not installed on ${targeta}"
    print_FAIL
  else
    pad " · Ensuring that the required environment is ready on ${targeta}"
    if ${ssh} ${targeta} "rpm -q --quiet ${reqd_package}"
    then
      print_SUCCESS
    else
      print_FAIL
    fi

    pad " · Backing up ${log_preserve_conf} on ${targeta}"
    if ${ssh} ${targeta} "cp ${log_preserve_conf} /tmp/" &&
       ${ssh} ${targeta} "test -f /tmp/journald.conf"
    then
      print_SUCCESS
    else
      print_FAIL
    fi

    print_line
  fi
}

function lab_finish {

  print_header "Completing the lab on ${targeta}:"
  host_reachable ${targeta}

  reqd_package='systemd'        # Just an example

  pad " · Ensuring that the required environment is clean on ${targeta}"
  if ${ssh} ${targeta} "rpm -q --quiet ${reqd_package}"
  then
    print_SUCCESS
  else
    print_FAIL
  fi

  pad " · Restoring original ${log_preserve_conf} on ${targeta}"
  if ! ${ssh} ${targeta} "test -e /tmp/journald.conf"
  then
    print_SUCCESS
  else
    if ${ssh} ${targeta} "cp /tmp/journald.conf ${log_preserve_conf}" &&
       ${ssh} ${targeta} "rm -f /tmp/journald.conf" &&
       ${ssh} ${targeta} "systemctl restart systemd-journald.service" &&
       ${ssh} ${targeta} "rm -rf /var/log/journal/"
    then
      print_SUCCESS
    else
      print_FAIL
    fi
  fi

  print_line
  print_line 'Lab finished.'
  print_line
}

############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
