#!/bin/bash
#
# Copyright 2019 Red Hat, Inc.
#
# NAME
#     lab-net-validate - grading script for RH124 Guided Exercise
#                        Validating Network Configuration
#
# SYNOPSIS
#     lab-net-validate {start|finish}
#
#        start   - prepare the system for starting the lab
#        finish  - perform post-lab cleanup
#
# DESCRIPTION
#     This script, based on singular argument, either does start or
#     finish for the Validating Network Configuration guided exercise.
#
# CHANGELOG
#   * Thu Feb 07 2019 Victor Costea <vcostea@redhat.com>
#   - original code

PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Initialize and set some variables
run_as_root='true'
target='servera'

# This defines which subcommands are supported (start, grade, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(start finish)


function lab_start {

  print_header 'Starting lab.'

  print_line "Preparing ${target} for lab exercise work:"
  print_line
  pad " · Check ${target} connectivity"
  host_reachable ${target}
  print_SUCCESS

  print_line
}


function lab_finish {

  print_header "Cleaning up the lab on ${target}:"

  pad " · Check ${target}"
  host_reachable ${target}
  print_SUCCESS

  print_line
  print_line 'Lab finished.'
  print_line
}

############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
