#!/bin/bash
#
# Copyright 2019 Red Hat, Inc.
#
# NAME
#     lab-software-rpm - Start script for Guided Exercise Examining
#                        RPM Package Files
#
# SYNOPSIS
#     lab-software-rpm {start|finish}
#
#        start   - prepare the system for starting the lab
#        finish  - perform post-lab cleanup
# DESCRIPTION
#     This script verifies servera is accessible, downloads the package,
#     remove any lab artifacts.
#
# CHANGELOG
#   * Thu Mar 07 2019 Snehangshu Karmakar <snehk@redhat.com>
#   - original code

PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Initialize and set some variables
run_as_root='true'
target='servera'
content_rhel_ver='rhel8.2'
reqd_package='yum'
loc="http://content.example.com/${content_rhel_ver}/x86_64/rhcsa-practice/rht/Packages/"
pkgname='rhcsa-script'
rpmname='rhcsa-script-1.0.0-1.noarch.rpm'
# This defines which subcommands are supported (start, grade, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(start finish)


function lab_start {
  print_header 'Starting lab.'

  print_line "Preparing ${target} for lab exercise work:"
  print_line
  # Check that target host is reachable.
  pad " · Verifying server is reachable: ${target}"
  host_reachable ${target}
  print_SUCCESS

  #Download the package
  pad " · Downloading the package: ${target}"
  if ${ssh} ${target} "su - student -c 'curl -s -f -o ${rpmname} ${loc}/${rpmname}'"; then
    print_SUCCESS
  else
    print_FAIL
  fi

  # Check that required package(s) is/are installed.
  pad " · Verifying package: ${reqd_package}"
  cmd1="yum -y install ${reqd_package}"
  if  ${ssh} ${target} "rpm -q --quiet ${reqd_package}"; then
    print_SUCCESS
  elif  ${ssh} ${target} "${cmd1}"; then
    print_SUCCESS
  else
    print_FAIL
  fi

  pad " · Verifying exercise package is not installed: ${target}"
  cmd1="yum -y remove ${pkgname}"
  if  ! ${ssh} ${target} "rpm -q --quiet ${pkgname}"; then
    ${ssh} ${target} "touch /etc/motd"
    print_SUCCESS
  else
    ${ssh} ${target} "${cmd1}"
    ${ssh} ${target} "rm -rf /home/student/opt"
    ${ssh} ${target} "touch /etc/motd"
    print_SUCCESS
  fi

  print_line
}
function lab_finish {

  print_header "You have completed attempting the guided exercise."
  host_reachable ${target}

  pad " · Removing package: ${pkgname}"
  cmd1="yum -y remove ${pkgname}"
  if  ! ${ssh} ${target} "rpm -q --quiet ${pkgname}"; then
    print_SUCCESS
  else
    ${ssh} ${target} "${cmd1}"
    print_SUCCESS
  fi

  pad " · Removing files: ${target}"
  cmd1="rm -rf /home/student/opt /etc/motd"
  if  ${ssh} ${target} "${cmd1}"; then
    print_SUCCESS
  fi

  print_line
  print_line 'Lab finished.'
  print_line
}


############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"

