#!/bin/bash
#
# Copyright 2019 Red Hat, Inc.
#
# NAME
#     lab-tuning-profiles - grading script for RH134 Guided Exercise
#                           Adjusting Tuning Profiles
#
# SYNOPSIS
#     lab-tuning-profiles {start|grade|finish}
#
#        start   - prepare the system for starting the lab
#        finish  - perform post-lab cleanup
#
# DESCRIPTION
#     This script, based on singular argument, either does start or
#     finish for the Adjusting Tuning Profiles guided exercise.
#
# CHANGELOG
#   * Wed Mar 20 2019 Victor Costea <vcostea@redhat.com>
#   - original code

PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Initialize and set some variables
run_as_root='true'
target='servera'

# This defines which subcommands are supported (start, grade, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(start finish)


function lab_start {

  print_header 'Starting lab.'

  print_line "Preparing ${target} for lab exercise work:"
  print_line

  pad " · Check ${target} connectivity"
  host_reachable ${target}
  print_SUCCESS

  print_line
}

function lab_finish {

  default_profile='virtual-guest'
  is_tuned_installed='yum list installed | grep tuned'
  set_default_profile="tuned-adm profile ${default_profile}"

  print_header "Cleaning up the lab on ${target}:"
  host_reachable ${target}

# If tuned is at least installed, running or not, the 
# "tuned-adm profile <profile>" command will start the service 
# and activate the <profile>.

  pad " · Set active tuning profile to ${default_profile}"
  if ${ssh} ${target} "${is_tuned_installed}"; then
    ${ssh} ${target} "${set_default_profile}"
    print_SUCCESS
  else
    print_FAIL
  fi

  print_line
  print_line 'Lab finished.'
  print_line
}

############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
