#!/bin/bash
#
# Copyright 2020 Red Hat, Inc.
#
# NAME
#     lab-containers-basic - lab script for RH134 Running a Basic Container guided exercise
#
# SYNOPSIS
#     lab-containers-basic {start | finish}
#
#        start   - prepare the system for starting the lab
#        finish  - perform post-lab cleanup
#
# DESCRIPTION
#     This script, based on singular argument, either does start
#     or finish for the guided exercise
#
# CHANGELOG
#   * Thu Aug 20 2020 Herve Quatremain <hquatrem@redhat.com>
#   - original code
#   * Thu Aug 20 2020 Ed Parenti <eparenti@redhat.com>
#   - revised per testing and added check for images in registry

PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Initialize and set some variables
run_as_root='true'
target='servera'

# This defines which subcommands are supported (start, grade, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(start finish)


function lab_start {

  print_header 'Starting lab.'

  print_line "Preparing ${target} for lab exercise work:"
  print_line
  host_reachable ${target}

  rhel_containers_check_quay

  rhel_containers_add_registry_DNS ${target} && \
  rhel_containers_add_repository ${target} && \
  rhel_containers_configure_quay_client ${target}

  rhel_containers_inspect_image admin redhat321 registry.lab.example.com/rhel8/httpd-24 Digest

  print_line
}


function lab_finish {

  print_header "Cleaning up the lab on ${target}:"
  host_reachable ${target}

  rhel_containers_undeploy_client ${target}

  print_line
  print_line 'Lab finished.'
  print_line
}

############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"

