#!/bin/bash
#
# Copyright 2019 Red Hat, Inc.
#
# NAME
#     lab-fs-locate - grading script for RH124 Guided Exercise
#                     Locating Files on the System
#
# SYNOPSIS
#     lab-fs-locate {start|finish}
#
#        start   - prepare the system for starting the lab
#        finish  - perform post-lab cleanup
#
# DESCRIPTION
#     This script, based on singular argument, either does start,
#     or finish for the Locating Files on the System
#     Guided Exercise.
#
# CHANGELOG
#   * Wed Feb 20 2019 Snehangshu Karmakar <snehk@redhat.com>
#   - original code

PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Initialize and set some variables
run_as_root='true'
target='servera'

# This defines which subcommands are supported (start, grade, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(start finish)

function lab_start {

  print_header 'Starting lab.'

  print_line "Preparing ${target} for lab exercise work:"
  print_line

  pad " · Verifying server is reachable: ${target}"
  host_reachable ${target}
  print_SUCCESS

  print_line
}

function lab_finish {

  print_header "You have completed attempting the guided exercise."
  host_reachable ${target}
  
  print_line 'Lab finished.'
  print_line
}

############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
