#!/bin/bash
#
# Copyright 2019 Red Hat, Inc.
#
# NAME
#     lab-edit-shell - grading script for RH124 Changing the Shell Environment 
#
# SYNOPSIS
#     lab-edit-review {start|finish}
#
#        start   - prepare the system for starting the lab
#        finish  - perform post-lab cleanup
#
# DESCRIPTION
#     This script, based on singular argument, either does start
#     or finish for Changing the Shell Environment guided exercise.
#
# CHANGELOG
#   * Tue May 28 2019 Victor Costea <vcostea@redhat.com>
#   - Add code to backup student's .bashrc in start
#   - Add code to restore student's .bashrc in finish
#   * Wed Jan 23 2019 Fiona Allen <fallen@redhat.com>
#   - original code

PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Initialize and set some variables
run_as_root='true'
target='servera'
ch05s06_bashrc='/home/student/.bashrc'

# This defines which subcommands are supported (start, grade, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(start finish)


function lab_start {

  print_header 'Starting lab.'

  print_line "Preparing workstation for lab exercise work:"
  print_line

  pad " · Verifying that ${target} is running: "
  if host_reachable ${target}
  then
    print_SUCCESS
  else
    print_FAIL
  fi

  pad " · Creating the temporary file: "
  if ${ssh} student@${target} touch tmp.zdkei083
  then
    print_SUCCESS
  else
    print_FAIL
  fi

## E2E QA backup .bashrc
  pad " · Backup ~/.bashrc "
  if ! ${ssh} ${target} "test -f ${ch05s06_bashrc}.orig"
  then
    ${ssh} student@${target} "cp ${ch05s06_bashrc}{,.orig}"
    print_SUCCESS
  elif ${ssh} ${target} "test -f ${ch05s06_bashrc}.orig"
  then
    print_SUCCESS
  else
    print_FAIL
  fi

  print_line

}

function lab_finish {

  print_header "Completing the lab on workstation:"
  host_reachable ${target}

  pad " · Deleting the temporary file: "
  if ${ssh} ${target} '[[ ! -f /home/student/tmp.zdkei083 ]]'
  then
    print_SUCCESS
  elif ${ssh} ${target} "rm /home/student/tmp.zdkei083"
  then
    print_SUCCESS
  else
    print_FAIL
  fi

## E2E QA restore .bashrc
  pad " · Restore ~/.bashrc "
  if ${ssh} ${target} "test -f ${ch05s06_bashrc}.orig"
  then
    ${ssh} student@${target} "mv ${ch05s06_bashrc}{.orig,}"
    print_SUCCESS
  elif ! ${ssh} ${target} "test -f ${ch05s06_bashrc}.orig"
  then
    print_SUCCESS
  else
    print_FAIL
  fi

  print_line
  print_line 'Lab finished.'
  print_line

}

############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
