#!/bin/bash
#
# Copyright 2019 Red Hat, Inc.
#
# NAME
#     lab-ssh-access - grading script for RH124 Accessing the Remote Command Line with SSH
#
# SYNOPSIS
#     lab-ssh-access {start|finish}
#
#        start   - prepare the system for starting the lab
#        finish  - perform post-lab cleanup
#
# DESCRIPTION
#     This script, based on singular argument, either does start
#     or finish for the particular lab of awesomeness.
#
# CHANGELOG
#   * Fri Feb 01 2019 Saumik Paul <saumik@redhat.com>
#   - original code

PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Initialize and set some variables
run_as_root='true'
targeta='servera'
targetb='serverb'
known_hosts=/home/student/.ssh/known_hosts
#ge_user1='operator1'
#ge_user2='operator2'
#ge_user3='operator3'
#ge_user_pw='redhat'
#passwd='/etc/passwd'
#shadow='/etc/shadow'

# This defines which subcommands are supported (start, grade, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(start finish)


function lab_start {

  reqd_package='openssh-clients'        # Just an example

  print_header 'Starting lab.'

  print_line "Preparing ${targeta} and ${targetb} for lab exercise work:"
  print_line
  host_reachable ${targeta} ${targetb}


  # Check for lab prerequisites (perhaps a required package?).
  if ! ${ssh} ${targeta} "rpm -q --quiet ${reqd_package}"
  then
    pad " · Error - ${reqd_package} is not installed on ${targeta}"
    print_FAIL
  else
    pad " · Ensuring known_hosts file does not exist on ${targeta}"
    if ! ${ssh} ${targeta} "test -e ${known_hosts}"
    then
      print_SUCCESS
    else
      ${ssh} ${targeta} "rm -f ${known_hosts}" 
      if ! ${ssh} ${targeta} "test -f ${known_hosts}" 
      then
	print_SUCCESS
      else
	print_FAIL
      fi
    fi

    print_line
  fi
}

function lab_finish {

  print_header "Completing the lab on ${targeta}:"
  host_reachable ${target}

  pad " · Deleting known_hosts file from ${targeta}"
  if ${ssh} ${targeta} "rm -f ${known_hosts}" &&
     ! ${ssh} ${targeta} "test -f ${known_hosts}"
  then
    print_SUCCESS
  else
    print_FAIL
  fi    

  print_line
  print_line 'Lab finished.'
  print_line
}

############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
