#!/bin/bash
#
# Copyright 2019 Red Hat, Inc.
#
# NAME
#     lab-perms-default - grading script for RH124 Managing Default Permissions and File Access 
#                    Guided Exercise
# SYNOPSIS
#     lab-perms-default {start|finish}
#
#        start   - prepare the system for starting the lab
#        finish  - perform post-lab cleanup
#
# DESCRIPTION
#     This script, based on singular argument, either does start,
#     or finish for the Managing Default Permissions and File Access
#     guided exercise.
#
# CHANGELOG
#   * Mon Feb 04 2019 Fiona Allen <fallen@redhat.com>
#   - original code

PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Initialize and set some variables
run_as_root='true'
target='servera'
group='operators'
user1='operator1'
user2='operator2'
directory='/tmp/shared'


# This defines which subcommands are supported (start, grade, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(start finish)


function lab_start {

  print_header 'Starting lab.'

  print_line "Preparing ${target} for lab exercise work:"
  print_line

  pad " · Verifying that ${target} is running: "
  if host_reachable ${target}
  then
    print_SUCCESS
  else
    print_FAIL
  fi

  pad " · Creating group: ${group}"
  if ${ssh} ${target} "getent group ${group}" | grep 40000; then
    print_SUCCESS
  else
    if ${ssh} ${target} "groupadd -g 40000 ${group}"
    then
      print_SUCCESS
    else
      print_FAIL
    fi
  fi  

  pad " · Creating user: ${user1}"
  if ${ssh} ${target} "id ${user1}"; then
    if ${ssh} ${target} "id ${user1} | grep ${group}"; then
      print_SUCCESS
    else
      ${ssh} ${target} "usermod ${user1} -G ${group}"
      print_SUCCESS
    fi
  else 
    ${ssh} ${target} "useradd ${user1} -G ${group}"
    if ${ssh} ${target} "echo 'redhat' | sudo passwd --stdin ${user1}"; then
      print_SUCCESS
    else
      print_FAIL
    fi
  fi
  print_line
}

function lab_finish {

  print_header "Completing the lab on ${target}:"
  host_reachable ${target}
  
  pad " · Deleting user: ${user1}"
  if ${ssh} ${target} "id ${user1}"
  then
    ${ssh} ${target} "userdel -r ${user1}"
    print_SUCCESS
  else
   print_SUCCESS
  fi

  pad " · Deleting group ${group}: "
  if ${ssh} ${target} "getent group ${group}"
  then
    ${ssh} ${target} "groupdel ${group}"
    print_SUCCESS
  else
    print_SUCCESS
  fi
 
  pad " · Deleting ${directory}: "
  if ${ssh} ${target} [[ -d ${directory} ]]
  then
    ${ssh} ${target} "rm -rf ${directory}"
    print_SUCCESS
  else
    print_SUCCESS
  fi

  print_line
  print_line 'Lab finished.'
  print_line

}

############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
