#!/bin/bash
#
# Copyright 2019 Red Hat, Inc.
#
# NAME
#     lab-software-repo - Start script for Guided Exercise Enabling Yum
#                         Software Repositories
#
# SYNOPSIS
#     lab-software-repo {start|finish}
#
#        start   - prepare the system for starting the lab
#        finish  - perform post-lab cleanup
#
# DESCRIPTION
#     This script, based on singular argument, either does start or finish for
#     the Enabling Yum Software Repositories guided exercise.
#
# CHANGELOG
#   * Wed Feb 27 2019 Marc Kesler <rkesler@redhat.com>
#   - original code

PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Initialize and set some variables
run_as_root='true'
target='servera'
pkgname='rht-system'
# This defines which subcommands are supported (start, grade, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(start finish)


function lab_start {
  print_header 'Starting lab.'

  print_line "Preparing ${target} for lab exercise work:"
  print_line
  host_reachable ${target}

  pad " · Verifying exercise software repos are absent on ${target}"
  ${ssh} ${target} "yum repolist -v all | awk -F': ' '\$1 ~ /Repo-baseurl/ && \$2 ~ /rhcsa-practice/ { found=1; } \$1 ~ /Repo-filename/ && found==1 { print \$2; found=0;}' | xargs rm"
  print_SUCCESS

  print_line
}

function lab_finish {

  print_header "Cleaning up the lab on ${target}:"
  host_reachable ${target}

  pad " · Removing the ${pkgname} package on ${target}"
  ${ssh} ${target} "yum -y remove ${pkgname}"
  print_SUCCESS

  pad " · Removing exercise software repos on ${target}"
  ${ssh} ${target} "yum repolist -v all | awk -F': ' '\$1 ~ /Repo-baseurl/ && \$2 ~ /rhcsa-practice/ { found=1; } \$1 ~ /Repo-filename/ && found==1 { print \$2; found=0;}' | xargs rm"
  print_SUCCESS

  print_line
  print_line 'Lab finished.'
  print_line
}


############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
