#!/bin/bash
#
# Copyright 2019 Red Hat, Inc.
#
# NAME
#     lab-help-manual - grading script for RH124 Reading Manual Pages 
#
# SYNOPSIS
#     lab-edit-review {start|grade|finish}
#
#        start   - prepare the system for starting the lab
#        grade   - perform evaluation steps on the system
#        finish  - perform post-lab cleanup
#
# DESCRIPTION
#     This script, based on singular argument, either does start, grading,
#     or finish for the particular lab of awesomeness.
#
# CHANGELOG
#   * Mon Feb 25 2019 Fiona Allen <fallen@redhat.com>
#   - original code

PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Initialize and set some variables
run_as_root='true'
target='servera'
file='/home/student/manual'

# This defines which subcommands are supported (start, grade, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(start finish)


function lab_start {

  print_header 'Starting lab.'

  print_line "Preparing workstation for lab exercise work:"
  print_line

  pad " · Verifying that ${target} is running: "
  if host_reachable ${target}
  then
    print_SUCCESS
  else
    print_FAIL
  fi

  pad " · Creating test file ${file}: "
  if [ -f $file ]
  then
    print_SUCCESS
  else
    if echo "the quick brown fox just came over to greet the lazy poodle!" > ${file}
    then 
      sudo chown student:student ${file} && print_SUCCESS
    else
      print_FAIL
    fi  
  fi

  pad " · Running man update: "
  if sudo mandb -c
  then
   print_SUCCESS
  else
   print_FAIL
  fi


  print_line

}

function lab_finish {

  print_header "Completing the lab on workstation:"
  host_reachable ${target}

  pad " · Remove ${file}: "
  if [ -f $file ]
  then
    rm -f ${file} && print_SUCCESS
    else
    if [ ! -f $file ]
    then
      print_SUCCESS
    else
      print_FAIL
    fi
  fi

  print_line
  print_line 'Lab finished.'
  print_line

}

############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
