#!/bin/bash
#
# Copyright 2019 Red Hat, Inc.
#
# NAME
#     lab-software-yum - Start script for Guided Exercise Installing and
#                        Updating Software with yum
#
# SYNOPSIS
#     lab-software-yum {start|finish}
#
#        start   - prepare the system for starting the lab
#        finish  - perform post-lab cleanup
# DESCRIPTION
#     This script verifies servera is accessible and that yum is installed.
#
# CHANGELOG
#   * Wed Feb 20 2019 Marc Kesler <rkesler@redhat.com>
#   - original code

PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Initialize and set some variables
run_as_root='true'
target='servera'

# This defines which subcommands are supported (start, grade, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(start finish)


function lab_start {

  reqd_package='yum'

  print_header 'Starting lab.'

  print_line "Preparing ${target} for lab exercise work:"
  print_line
  host_reachable ${target}

    # Check that required package(s) is/are installed.
  pad " · Check that ${reqd_package} is installed on ${target}"
  cmd1="yum -y install ${reqd_package}"
  if  ${ssh} ${target} "rpm -q --quiet ${reqd_package}"; then
    print_SUCCESS
  elif  ${ssh} ${target} "${cmd1}"; then
    print_SUCCESS
  else
    print_FAIL
  fi

  print_line
}

function lab_finish {

  print_header "Cleaning up the lab on ${target}:"
  host_reachable ${target}

  pad " · Removing lab packages from ${target}"
  cmd1='yum remove -y guile'
  cmd2='yum group remove -y "RPM Development Tools" "Security Tools"'
  ${ssh} ${target} "${cmd1}"
  ${ssh} ${target} "${cmd2}"
  print_SUCCESS

  print_line
  print_line 'Lab finished.'
  print_line
}


############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
