#!/bin/bash
#
# Copyright 2019, 2020 Red Hat, Inc.
#
# NAME
#     lab-help-manual - grading script for RH124 Reading Info Documentation
#
# SYNOPSIS
#     lab-edit-review {start|finish}
#
#        start   - prepare the system for starting the lab
#        finish  - perform post-lab cleanup
#
# DESCRIPTION
#     This script, based on singular argument, either does start
#     or finish for the RH124 Reading Info Documentation exercise.
#
# CHANGELOG
#   * Thu Aug 27 2020 Herve Quatremain <hquatrem@redhat.com>
#   - Fixing Jira RH124-568
#   * Thu May 16 2019 Fiona Allen <fallen@redhat.com>
#   - improved finish script.
#   * Tue Feb 26 2019 Fiona Allen <fallen@redhat.com>
#   - original code

PATH=/usr/bin:/bin:/usr/sbin:/sbin

# This defines which subcommands are supported (start, grade, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(start finish)


function lab_start {

  print_line
  print_line 'Lab ready.'
  print_line

}

function lab_finish {

  print_line
  print_line 'Lab finished.'
  print_line

}

############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
